Repository hmcts/azure-platform-terraform, pull requests merged in 2025-06, with the labels that each got.

#2500 CCD-6381 Correct int component names
  environments/demo/backend_lb_config.yaml
Labels: 765: dev_global - TerraformPlanApply/add-or-update, 765: aat_global - TerraformPlanApply/add-or-update, 765: sbox_apim - TerraformPlanApply/no-changes, 765: stg_apim - TerraformPlanApply/no-changes, 765: ithc_apim - TerraformPlanApply/no-changes, 765: test_apim - TerraformPlanApply/no-changes, 765: demo_apim - TerraformPlanApply/no-changes, 765: demo_private_dns - TerraformPlanApply/destroy

#2502 ADOP-2484: Update rules - allow details of document uploads through firewall
  environments/ithc/ithc.tfvars
Labels: 765: dev_global - TerraformPlanApply/add-or-update, 765: aat_global - TerraformPlanApply/add-or-update, 765: sbox_apim - TerraformPlanApply/no-changes, 765: stg_apim - TerraformPlanApply/no-changes, 765: ithc_apim - TerraformPlanApply/no-changes, 765: test_apim - TerraformPlanApply/no-changes, 765: demo_apim - TerraformPlanApply/no-changes

#2504 ADOP-2484: Enable prevention mode in PERFTEST and AAT, update global exclusions in DEMO
  environments/demo/demo.tfvars
  environments/stg/stg.tfvars
  environments/test/test.tfvars
Labels: 765: dev_global - TerraformPlanApply/add-or-update, 765: aat_global - TerraformPlanApply/add-or-update, 765: sbox_apim - TerraformPlanApply/no-changes, 765: stg_apim - TerraformPlanApply/no-changes, 765: ithc_apim - TerraformPlanApply/no-changes, 765: test_apim - TerraformPlanApply/no-changes, 765: demo_apim - TerraformPlanApply/no-changes

#2503 Added waf exclusion for general apps document uploads in aat/preview
  environments/stg/stg.tfvars
Labels: 765: dev_global - TerraformPlanApply/add-or-update, 765: aat_global - TerraformPlanApply/add-or-update, 765: sbox_apim - TerraformPlanApply/no-changes, 765: stg_apim - TerraformPlanApply/no-changes, 765: ithc_apim - TerraformPlanApply/no-changes, 765: test_apim - TerraformPlanApply/no-changes, 765: demo_apim - TerraformPlanApply/no-changes

#2509 Add back 00 prod cluster
  environments/prod/prod.tfvars
Labels: 765: dev_global - TerraformPlanApply/add-or-update, 765: aat_global - TerraformPlanApply/add-or-update, 765: sbox_apim - TerraformPlanApply/no-changes, 765: stg_apim - TerraformPlanApply/no-changes, 765: ithc_apim - TerraformPlanApply/no-changes, 765: test_apim - TerraformPlanApply/no-changes, 765: demo_apim - TerraformPlanApply/no-changes

#2510 Remove 01 prod from gateway
  environments/prod/prod.tfvars
Labels: 765: dev_global - TerraformPlanApply/add-or-update, 765: aat_global - TerraformPlanApply/add-or-update, 765: sbox_apim - TerraformPlanApply/no-changes, 765: stg_apim - TerraformPlanApply/no-changes, 765: ithc_apim - TerraformPlanApply/no-changes, 765: test_apim - TerraformPlanApply/no-changes, 765: demo_apim - TerraformPlanApply/no-changes

#2514 Remove 00 prod from gateway
  environments/prod/prod.tfvars
Labels: 765: dev_global - TerraformPlanApply/add-or-update, 765: aat_global - TerraformPlanApply/add-or-update, 765: sbox_apim - TerraformPlanApply/no-changes, 765: stg_apim - TerraformPlanApply/no-changes, 765: ithc_apim - TerraformPlanApply/no-changes, 765: test_apim - TerraformPlanApply/no-changes, 765: demo_apim - TerraformPlanApply/no-changes

#2515 Add 00 prod to gateway
  environments/prod/prod.tfvars
Labels: 765: dev_global - TerraformPlanApply/add-or-update, 765: aat_global - TerraformPlanApply/add-or-update, 765: sbox_apim - TerraformPlanApply/no-changes, 765: stg_apim - TerraformPlanApply/no-changes, 765: ithc_apim - TerraformPlanApply/no-changes, 765: test_apim - TerraformPlanApply/no-changes, 765: demo_apim - TerraformPlanApply/no-changes

#2517 DO NOT MERGE Add prod 01 cluster to gateway
  environments/prod/prod.tfvars
Labels: 765: dev_global - TerraformPlanApply/add-or-update, 765: aat_global - TerraformPlanApply/add-or-update, 765: sbox_apim - TerraformPlanApply/no-changes, 765: stg_apim - TerraformPlanApply/no-changes, 765: ithc_apim - TerraformPlanApply/no-changes, 765: test_apim - TerraformPlanApply/no-changes, 765: demo_apim - TerraformPlanApply/no-changes

#2519 ADOP-2484: Enable prevention mode in PROD
  environments/prod/prod.tfvars
Labels: 765: dev_global - TerraformPlanApply/add-or-update, 765: aat_global - TerraformPlanApply/add-or-update, 765: sbox_apim - TerraformPlanApply/no-changes, 765: stg_apim - TerraformPlanApply/no-changes, 765: ithc_apim - TerraformPlanApply/no-changes, 765: test_apim - TerraformPlanApply/no-changes, 765: demo_apim - TerraformPlanApply/no-changes

#2527 ET1 fix to prevent firewall from blocking
  environments/demo/demo.tfvars
Labels: 765: dev_global - TerraformPlanApply/add-or-update, 765: aat_global - TerraformPlanApply/add-or-update, 765: sbox_apim - TerraformPlanApply/no-changes, 765: stg_apim - TerraformPlanApply/no-changes, 765: ithc_apim - TerraformPlanApply/no-changes, 765: test_apim - TerraformPlanApply/no-changes, 765: demo_apim - TerraformPlanApply/no-changes, 765: prod_global - TerraformPlanApply/destroy, 765: sbox_apim_appgw - TerraformPlanApply/destroy, 765: prod_apim_appgw - TerraformPlanApply/destroy, 765: stg_apim_appgw - TerraformPlanApply/destroy, 765: test_apim_appgw - TerraformPlanApply/destroy, 765: demo_apim_appgw - TerraformPlanApply/destroy
